### ISSUE TITLE
Non-posts in posts folder

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/coding-blog-boilerplate#4]
The contents of the [`posts` folder](https://github.com/CONNECT-platform/coding-blog-boilerplate/tree/master/posts) includes
- 404.md
- _toc.md
- index.md

Since those files are not posts, this was surprising to me.

**Comment by TysonMN** [comment]
Here are some names that I think are better than `posts`:
1. `src`
2. `md`
3. `markdown`

I going with `markdown` in my repo for now.

If it would be helpful, I can make a PR to change this.

**Comment by loreanvictor** [comment]
That folder is the intended home for your blog posts, hence the `posts` name. I thought `src` might be a bit out of context since mostly blog repos should contain blog posts.

Everyone has their own preference naturally, and definitely coding.blog/codedoc should be configurable enough to easily allow people to restructure their repos as they see fit.
